"use client";
import Image from "next/image";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <div className="m-auto text-center w-full">
        {/* <Image src={"/assets/images/mitramedia.svg"} alt="Picture of the author" width={100} height={100} className="w-full"/> */}

        <div className="m-auto bg-logo_corp dark:bg-logo_corp_dark w-[21%] h-[80px] bg-no-repeat"></div>

        <p className="text-lg mt-8">Halaman tidak di temukan</p>
        <Link href={"/"}>
          <p className="text-blue-500 cursor-pointer hover:underline mt-4">
            Kembali ke halaman utama &gt;&gt;
          </p>
        </Link>
      </div>
    </main>
  );
}
