"use client";
import Image from "next/image";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <div className="m-auto text-center w-full">
        <div className="justify-center items-center flex">
          <Image
            src={"/assets/images/mitramedia.webp"}
            alt="Logo Mitramedia Advertising"
            width={200}
            height={24}
            priority={true}
            className="aspect-auto block dark:hidden"
            quality={100}
          />
          <Image
            src={"/assets/images/mitramedia2.webp"}
            alt="Logo Mitramedia Advertising"
            width={200}
            height={24}
            priority={true}
            className="aspect-auto hidden dark:block"
            quality={100}
          />
        </div>

        <p className="text-sm mt-2">Halaman tidak di temukan</p>
        <Link href={"/"}>
          <p className="text-blue-500 text-sm cursor-pointer hover:underline mt-2">
            Kembali ke halaman utama &gt;&gt;
          </p>
        </Link>
      </div>
    </main>
  );
}
